_wandb:
    value:
        cli_version: 0.25.0
        e:
            myoosq3w8e0alyymut74yo3lyat8h3fl:
                args:
                    - --loss
                    - mse
                    - --activation
                    - relu
                    - --optimizer
                    - rmsprop
                    - --learning_rate
                    - "0.001"
                codePath: src\train.py
                codePathLocal: src\train.py
                cpu_count: 8
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "179743748096"
                        used: "137192226816"
                email: iitmgopal1@gmail.com
                executable: C:\Users\prani\OneDrive\Desktop\Sem-6 !\DL\da6401_assignment_1\.venv\Scripts\python.exe
                git:
                    commit: 0020080ceb275a0c6fa281ffb6c9ae869948e0c3
                    remote: https://github.com/Gopal1909/da6401_assignment_1.git
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 2560
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-015c1b9e-c36b-389d-cb4b-c0db25438efc
                host: Pranitha
                memory:
                    total: "16763871232"
                os: Windows-11-10.0.26200-SP0
                program: C:\Users\prani\OneDrive\Desktop\Sem-6 !\DL\da6401_assignment_1\src\train.py
                python: CPython 3.13.12
                root: C:\Users\prani\OneDrive\Desktop\Sem-6 !\DL\da6401_assignment_1
                startedAt: "2026-03-07T00:01:07.905945Z"
                writerId: myoosq3w8e0alyymut74yo3lyat8h3fl
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "4": 3.13.12
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: relu
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 10
hidden_size:
    value: 128,128
learning_rate:
    value: 0.001
loss:
    value: mse
model_save_path:
    value: src/best_model.npy
num_layers:
    value: 2
optimizer:
    value: rmsprop
wandb_project:
    value: da6401_assignment_1-src
weight_decay:
    value: 0
weight_init:
    value: xavier
